name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name : Run mvn package
      run: mvn clean package
    
    - name: mvn deploy
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/tataba -Dtoken=repo-token
      
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

